Hometask #19
idunskiy/TestingProject pull request #4
Opened 2020-07-04 07:58 UTC by idunskiy

2020-07-04 11:44 UTC, dbradul requested changes

2020-07-04 11:44 UTC, dbradul commented on src/testsuite/models.py
> +    def all_questions(self):
Рассмотрите название `question_count` для единообразия.

2020-07-04 11:48 UTC, dbradul approved these changes

2020-07-05 07:45 UTC, idunskiy commented on src/testsuite/models.py
> +    def all_questions(self):
Я специально так сделал, ведь может понадобиться потом возвращать все вопросы теста, а не только их кол-во.

2020-07-05 07:46 UTC, merged