Hometask #23
idunskiy/TestingProject pull request #6
Opened 2020-07-16 08:14 UTC by idunskiy

2020-07-16 11:46 UTC, dbradul requested changes

2020-07-16 11:46 UTC, dbradul commented on src/tests/test_models.py
> +        answers = 'answers_1', 'answers_3', 'answers_3'
А можно извлечь информацию о правильным ответах из самого теста, чтобы сделать unittest более универсальным и работающим с любым тестом?
Ведь информация какие ответы верные нам доступна, как и количество вопросов для сравнения с кол-вом правильных ответов.

2020-07-20 08:54 UTC, dbradul requested changes

2020-07-20 08:54 UTC, dbradul commented on src/tests/test_models.py
>          self.assertNotEqual(test_result.correct_answers_count(), 3)
Если вы убрали хардкод в ответах, то можно убрать его и тут.  Т.е. сравнить `correct_answers_count` с кол-вом вопросов.

2020-07-20 08:54 UTC, dbradul commented on src/tests/test_models.py
> +        return correct_answers
Можно сделать небольшую оптимизацию: 
```
answers = Answer.objects.select_related('question').all()
```
в таком случае выполнится 1 join-запрос. Сейчас у вас выполняется 1+N запросов (1 для всех вопросов, N - для каждого вопроса при чтении ответов).

2020-07-20 08:54 UTC, dbradul commented on src/tests/test_models.py
> +        _index = random.randint(1, len(_incorrect_answers))
Обычно лидирующее подчеркивание ставят для аттрибутов класса и функций, чтобы обозначить их приватность. 
Для переменных внутри функции это не нужно, т.к. область видимости переменных ограничена телом функции, т..е они уже приватны.

2020-07-20 09:48 UTC, idunskiy commented on src/tests/test_models.py
> +        return correct_answers
Хм, в этом случае answers ничего не возвращает.

2020-07-26 07:41 UTC, merged